"""empty message

Revision ID: 759fa486ca88
Revises: 7ccd1feca913
Create Date: 2023-10-21 15:30:14.222824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '759fa486ca88'
down_revision = '7ccd1feca913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
